openbr/gui/classifier.cpp
openbr/gui/classifier.h
openbr/gui/templatemetadata.cpp
openbr/gui/templatemetadata.h
openbr/openbr_plugin.h

The interface as discussed last night (as much as I remember)

Implementation of Classification Interface

---

openbr/core/eval.cpp

@bklare @sklum @bhklein As described.

break ties pessimistically

---

openbr/plugins/time.cpp

@JordanCheney This proposed rewrite of StopWatchTransform adds the following features:
1. Holds on to the transform description so that it can be printed, making it sensible to use multiple instantiations of StopWatch in the same algorithm.
2. Works with trainable transforms.
3. No longer locks on the child->project call, allowing for better parallelization.
Let me know if you think this introduces any regressions or is otherwise too invasive. Happy to tweak it or rename it as a separate transform.

rewrote StopWatchTransform

---

openbr/openbr_plugin.cpp
openbr/openbr_plugin.h

This should take care of the overhead to create the Representation and Classification abstractions in OpenBR. @jklontz @caotto could one of you review when you have time?

Update Classification API to support OpenBR object handling

---

openbr/janus_io.cpp

This constructs a QList of TemplatePair futures instead of making use of janus_gallery.  
_janus_create_flat_template creates and flattens a template given janus template metadata, returning pair of template_id and flat_template.  
biometrics/janus@af09b819687270e0a198941d275ffa2b42fcd52c was necessary in  order to use FlatTemplates as QFuture return values.

Maintain metadata order in OpenBR implementation of janus_create_templates

---

openbr/plugins/random.cpp

Randomly samples around a specified point to provide positive and negative samples to a classifier/regressor.

Implemented RndSample transform

---

openbr/plugins/filter.cpp
openbr/plugins/gui.cpp

This adds the ability to blur each region of interest stored in the file's rects list.

Blur regions of interest

---

openbr/plugins/misc.cpp

@jklontz Per earlier conversation.

Error message for ReadTransform

---

openbr/core/opencvutils.cpp
openbr/core/opencvutils.h
openbr/plugins/svm.cpp
openbr/plugins/tree.cpp

This branch cleans up our serialization of OpenCV's `CvStatModel`s by refactoring the code to be a utility.

Opencv model storage

---

openbr/plugins/mask.cpp

@imaus10 Any problems with the changes to your transform?

Mask updates

---

openbr/plugins/gallery/binary.cpp
openbr/universal_template.cpp
openbr/universal_template.h

b4:
$ br -algorithm Print -enroll test.ut
Set algorithm to Print
Enrolling test.ut
[AlgorithmID=-3, First_Eye=(25,226), FrameNumber=0, FrontalFace=(4.29497e+09,84,251,314), ImageID=f673aef982ba6bae572cc8ce9c79dffa, Label=0, Second_Eye=(112,235), URL=http://scontent-b.cdninstagram.com/hphotos-xfp1/outbound-distilleryimage5/t0.0-17/OBPTH/92884f767df311e3a36912172d8c639d_7.jpg]
after:
$ br -algorithm Print -enroll test.ut 
Set algorithm to Print
Enrolling test.ut
[AlgorithmID=-3, First_Eye=(25,226), FrameNumber=0, FrontalFace=(-44,84,251,314), ImageID=f673aef982ba6bae572cc8ce9c79dffa, Label=0, Second_Eye=(114,236), URL=http://scontent-b.cdninstagram.com/hphotos-xfp1/outbound-distilleryimage5/t0.0-17/OBPTH/92884f767df311e3a36912172d8c639d_7.jpg]

Change ut.X and ut.Y to int32_t for BBs outside the image

---

openbr/plugins/core/algorithms.cpp

This fixes changes made in the recent refactor.

Update call Bin from HistBin

---

openbr/plugins/metadata/averagepoints.cpp

A subset of the [previous pull request](https://github.com/biometrics/openbr/compare/averagePoints) (sans eye drawing). This is a new pull request since the previous pull request is not valid after recent refactor.

Added new transform

---

openbr/plugins/imgproc/cropfrommask.cpp
openbr/plugins/imgproc/threshold.cpp

Crops an image based on an image metadata Mask

Crop from mask 

---

openbr/core/cluster.cpp
openbr/core/cluster.h
openbr/openbr.cpp

separating k-NN graph computation and clustering is helpful in various ways. Our current br -cluster behavior is unchanged, and implementing new interfaces is now possible.

Decompose k-NN graph generation and clustering

---

openbr/plugins/gallery/empty.cpp

Not sure if this requires a pull request, but as I'm not the code owner...

Better file count for emptyGallery

---

openbr/plugins/io/download.cpp

Added fte to download

---

CMakeLists.txt
app/CMakeLists.txt
openbr/CMakeLists.txt

This branch introduces some logic that facilitates building packages other than the default package.

Thirdparty package

---

openbr/plugins/distance/emd.cpp

This branch introduces Earth Mover's Distance.

Emd distance

---

openbr/plugins/imgproc/cropfrommask.cpp

@bklare as the code owner, are you ok with these changes?  I added some edge case checks and refactored a bit because the variable names were confusing (e.g. `w` referred to the number of rows, not cols).

CropFromMask Tweaks

---

openbr/plugins/imgproc/blend.cpp

Added support for more than two matrices in blend.  @jklontz, tell me what I'm missing :smile:.

Blend tweak

---

openbr/core/core.cpp

FTE templates shouldn't be used to train distances.

Distance training with FTEs

---

openbr/plugins/cmake/dlib.cmake

Dlib cmake file now conforms to the new cmake structure. @sklum tapping you for review

fix to dlib cmake file

---

openbr/plugins/classification/boostedforest.cpp
openbr/plugins/classification/cascade.cpp
openbr/plugins/imgproc/rndaffine.cpp
openbr/plugins/imgproc/slidingwindow.cpp
openbr/plugins/representation/gradienthistogram.cpp
openbr/plugins/representation/haar.cpp
openbr/plugins/representation/mblbp.cpp
openbr/plugins/representation/random.cpp

This should have been included in the merge of the cascade branch. @sklum you are probably the best reviewer it should be quick.

Documentation for cascade branch transforms

---

openbr/janus.cpp
openbr/janus_io.cpp
openbr/plugins/distance/unit.cpp

This PR implements the changes made in biometrics/janus#17

Janus phase2 updates

---

openbr/plugins/metadata/grid.cpp

This branch adds a parameter to rotate the grid.  @jklontz?

Grid Rotation

---

.gitignore
CMakeLists.txt
openbr/plugins/classification/dlib.cpp
openbr/plugins/cmake/dlib.cmake

@sklum please review
@JordanCheney heads up

automatically build dlib by default

---

openbr/plugins/gallery/binary.cpp
openbr/universal_template.cpp
openbr/universal_template.h

This PR simplifies and generalizes the `.ut` file format based on lessons learnt. @sklum please review, @imaus10 heads up.

Refactored br_universal_template format

---

openbr/plugins/metadata/filtermetadata.cpp

A simple transform for filtering based on metadata.

Filter metadata

---

openbr/core/opencvutils.cpp
openbr/core/opencvutils.h
openbr/plugins/gallery/matlab.cpp
scripts/matlab/loadOpenBR.m

This is a new gallery function for quick and dirty export of templates into a format easily ingestable in other environments (e.g., matlab).

Output to gallery that can be ingested into matlab

---

openbr/janus.cpp
openbr/janus_io.cpp

Sorry forgot to add these changes earlier.
* Changed `janus_allocate_gallery` to `janus_open_gallery`, and `janus_free_gallery` to `janus_close_gallery`.
* removed `janus_enroll` and now finalize galleries with `janus_write_gallery`
@JordanCheney or @jklontz please review

Janus gallery updates

---

openbr/plugins/cluster/onlinerod.cpp

Transform to perform Rank-Order distance clustering.

Online Rank-Order distance clustering

---

openbr/openbr_plugin.cpp
openbr/openbr_plugin.h
openbr/plugins/classification/boostedforest.cpp
openbr/plugins/classification/cascade.cpp

Remove unnecessary function maxCatCount() from classifiers. @sklum can you review?

Remove maxCatCount from Classifier

---

openbr/core/qtutils.cpp
openbr/core/qtutils.h
openbr/gui/utility.cpp
openbr/gui/utility.h
openbr/plugins/gallery/empty.cpp

This branch moves some QtUtils to be exported under GUI utils because I've found them useful in that scope.  @jklontz?

Utility Update

---

scripts/matlab/LDA.m
scripts/matlab/PCA.m
scripts/matlab/PCA2.m

These are what the openbr implementations were originally based off of.

Matlab lda

---

docs/docs/api_docs/c_api/functions.md
openbr/core/plot.cpp

This PR addresses some of the issues raised in #390.
* Added separate plot options for DET, and IET
* Set default ticks to 10% increments.
* Allow setting of x-axis limits
* Specify log/linear axis
* Added option to plot first two metadata pages
* Added option to output metadata tables to csv files
* Updated plotting docs

Plotting customization

---

openbr/plugins/metadata/verifydetection.cpp

See algorithm comments for intent of this transform. Pretty straightforward transform.

Verify detection

---

docs/docs/api_docs/c_api/functions.md
openbr/core/plot.cpp
share/openbr/plotting/plot_utils.R

This PR doesn't add much outward facing usability but will hopefully make the plotting framework easier to work with from a development standpoint.  
next steps:
* bring detection and landmarking evaluation/plotting up to snuff with -eval and -plot
* consolidate some of the R code further
* add more options and plot customization
* write test(s) for plotting - it's difficult to see whether or not you've broken the R code without testing different plotting configurations

Move bulk of R code from plot.cpp to plot_utils.R

---

CMakeLists.txt

@jklontz Per earlier conversation.

Add thirdparty_dir to cmake cache

---

openbr/plugins/classification/dlib.cpp

@sklum can you review?
I am running into a edge case where I need to pass a cropped face into the DLandmarker transform. The transform currently requires a face rect and an image as input, so this introduces a case where if no rect is present the entire image is considered a rect.

DLandmarker with no rect specified

---

openbr/plugins/cluster/meanshift.cpp

This is an implementation of the meanshift clustering algorithm. It has the nice feature of not requiring the number of clusters to be known before clustering occurs.
@caotto could you review?

Meanshift clustering

---

app/br/br.cpp
docs/docs/install.md
openbr/plugins/cmake/dlib.cmake
openbr/plugins/core/algorithms.cpp
openbr/plugins/imgproc/cropfromlandmarks.cpp
openbr/plugins/imgproc/scalemat.cpp
openbr/plugins/metadata/cascade.cpp
scripts/BTASTutorial/representation.sh
scripts/evalFaceRecognition-BLUFR.sh
share/openbr/plotting/plot_utils.R

This branch introduces updates to OpenBR's FR algorithm in preparation for the next tagged release
* New component based FR algorithm with improved performance on "unconstrained" imagery.
* New script for training/testing on the BLUFR LFW protocol
* updates to installation documentation

Openbr 1 0

---

openbr/plugins/distance/unit.cpp

Respect scoreNormalization flag in UnitDistance.

---

docs/docs/api_docs/cl_api.md

@JordanCheney I probably could have just committed this to master, but haven't edited the docs before so did a PR

Added cross validate info

---

openbr/plugins/classification/cascade.cpp
openbr/plugins/imgproc/slidingwindow.cpp

@JordanCheney these changes allow for multiple channel inputs to cascade+sliding window (i.e. not just grayscale). mind reviewing?

Updates to sliding window framework

---

openbr/plugins/imgproc/slidingwindow.cpp

@sklum Here's my first pass through the code. This just does the obvious stuff like hoisting invariants outside of loops, removing redundant variables, improving const correctness, etc. This reduced the runtime on my test case by 30% (from 83 to 58 seconds). Comments inline. @JordanCheney FYI.

SlidingWindow Cleanup

---

openbr/plugins/representation/haar.cpp

@sklum will you do the honors?

allocate less memory

---

scripts/downloadDatasets.sh

The tests failed for me because the data was never downloaded appropriately.
This is version one of the edits I am making to "downloadData.sh".
Hope it helps.

added "-p" for mkdir, fixed spelling mistake -> ./download{Meds,MEDS}.sh"

---

openbr/plugins/metadata/stopwatch.cpp

StopWatch currently only reports the projection time.  I modified the MetaTransform to print out the same report for training.

added timing report for training with StopWatch

---

openbr/plugins/cuda/cudapca.cpp

Moved the vector normalization to CUDA which gives a significant performance improvement

Further performance enhancements of CUDAPCA

---

openbr/core/utility.cpp
openbr/core/utility.h
openbr/plugins/gallery/empty.cpp

Updated empty gallery to use deepest folder as subject label

---

openbr/openbr_plugin.cpp

@jklontz This addresses the issue I was alluding to earlier.  Any problems?

Only use old metadata for an empty file

---

app/br/br.cpp
openbr/core/eval.cpp
openbr/core/eval.h
openbr/openbr.cpp
openbr/openbr.h

Added evaluation code for liveness

---

openbr/core/eval.cpp
openbr/plugins/classification/caffe.cpp
openbr/plugins/imgproc/roi.cpp
openbr/plugins/imgproc/rotate.cpp
openbr/plugins/metadata/extractvaluefromlist.cpp
openbr/plugins/metadata/majorityvoting.cpp
openbr/plugins/metadata/scorelevelfusion.cpp

…keys exist in the templates metadata
roi.cpp copyOnCrop=True is now the default
rotate.cpp rotates a mat by 90 intervals
extractvaluefromLlist.cpp extracts a single value from a list in metadata and saves it in a new key
majorityvoting.cpp Calculates which class has the highest scores when given a list of scores for each class
scorelevelfusion.cpp Fuses the scores together for each class when given a list of scores for each class

miscellaneous scripts 

---

app/br/br.cpp
openbr/core/eval.cpp
openbr/core/eval.h
openbr/core/evalutils.cpp
openbr/core/evalutils.h
openbr/openbr.cpp
openbr/openbr.h

Adds the ability to perform detection evaluation if bounding boxes also have a "Label" attached (i.e. object detection).

Add the ability to match object labels in the detection evaluation

---

docs/docs/install.md

openSUSE commands

---

openbr/core/core.cpp

transform `FileExclusion` was removed somewhere along the line and breaks gallery append functionality.

remove file exclusion on append

---

app/br/br.cpp
openbr/core/eval.cpp
openbr/core/eval.h
openbr/openbr.cpp
openbr/openbr.h
share/openbr/plotting/plot_utils.R

Simplified `InplaceEval` that makes use of a pre-computed mask rather than target and query files.

Inplace eval

---

openbr/core/tanh_sse.h

Remove `register` keyword (tanh_sse.h)

---

share/openbr/cmake/CodeCoverage.cmake

from https://raw.githubusercontent.com/bilke/cmake-modules/refs/heads/master/CodeCoverage.cmake

Add CodeCoverage.cmake
