openbr/core/core.cpp
openbr/openbr_plugin.h
openbr/plugins/distance.cpp
openbr/plugins/eigen3.cpp
openbr/plugins/keypoint.cpp
openbr/plugins/openbr_internal.h
openbr/plugins/pp5.cpp
openbr/plugins/quantize.cpp
openbr/plugins/sentence.cpp
openbr/plugins/turk.cpp
openbr/plugins/validate.cpp

@caotto @sklum @bklare The following PR introduces `virtual bool br::Distance::trainable()` and `br::UntrainableDistance`, the distance helper class analogy to `br::UntrainableTransform`. The purpose of this PR is to avoid projecting the training set through the enrollment pipeline, only to pass it to a distance that doesn't require any training. This is a substantial time saver for algorithms with untrainable distance metrics and large training sets.

introduced br::Distance::trainable() and UntrainableDistance

---

openbr/openbr_plugin.h
openbr/plugins/gallery.cpp

align didn't appear to improve speed, and allocating a single array for all template data is not feasible for large enough galleries

Remove memGallery::align and associated infrastructure

---

openbr/openbr_plugin.cpp
openbr/openbr_plugin.h
openbr/plugins/independent.cpp
openbr/plugins/meta.cpp
openbr/plugins/openbr_internal.h
openbr/plugins/stream.cpp

2 parts here, one is a refactor of setPropertyRecursive, so that the implementation is a little more general. Instead of implementing a method in every Transform with child transforms, the default implementation of setPropertyRecursive looks for Transform * and QList<Transform *> properties automatically. 
There are some limitations to this approach, in particular all transforms which use a QString property to store their child transforms description, rather than storing the child transform as a property still require special casing. It is perhaps worth reconsidering this idiom in general, since by this point using a QString property loses out on both automatic serialization of the child transform, and proper navigation of transform trees via reflection. 
Part 2, is as requested by …

Updates to stored transform handling

---

CMakeLists.txt

The build was failing for me because I have multiple versions of OpenCV installed on my system, and the CMake build was just using whatever the default OpenCV was, which in my case was an older version that didn't support some of the cascade API OpenBR was using.
The solution is to give the find_package command a minimum version requirement for OpenCV. I chose version 2.4.5 because that is documented at the following website: http://openbiometrics.org/doxygen/latest/linux_gcc.html

Adding a minimum version requirement for OpenCV (2.4.5)

---

app/br/br.cpp
openbr/core/eval.cpp
openbr/core/eval.h
openbr/core/plot.cpp
openbr/openbr.cpp
openbr/openbr.h
openbr/plugins/draw.cpp

This branch introduces functionality to evalLandmarking including:
* A sample image with ground truth landmarks drawn and labeled with their index that corresponds to later figures.
* Accurate and inaccurate testing examples.
* Table of average error rates for each landmark with confidence intervals.
* Reordered results in the normalized error plots such that they are sequential, as opposed to ordered by factor.
* Added options to draw to control the display of landmarks when using the `verbose` flag and to optionally display named points.
There is some duplication here with respect to the R code, which I can eliminate if this bothers anyone.
@bhklein @jklontz take a look?
Example posted in Slack.
Solves #302.

Eval landmark improvements

---

openbr/core/eigenutils.cpp
openbr/core/eigenutils.h
openbr/plugins/eigen3.cpp
openbr/plugins/stasm4.cpp

This branch refactors our eigen utilities in the following ways:
* All the utilities are now a part of the `EigenUtils` namespace
* The function `printEigen()` has been replaced with a templated `qDebug` operator
* The function `toEigen()` has been replaced with the OpenCV provided conversion functions.
* Write matrix has been optimized (@bklare, can you make sure it still provides the functionality you want?)
@jklontz @bklare please inspect.

Eigenutil cleanup

---

openbr/core/qtutils.cpp
openbr/core/qtutils.h

When serializing bytearrays in BlockCompression, explicitly use read/writeRawData instead of the default QDataStream serialization. QDataStream allegedly serializes byte arrays as quint32 length, followed by raw bytes, but in practice serialization failures occur in some circumstances (typically saving very large model files, involving multiple CvStatModel serializations), and are avoided (to my knowledge) by doing the documented serialization explicitly ourselves. 
This does not break binary compatibility, since it just explicitly does what the documentation claims QDataStream does.

Explicit bytearray serialization

---

openbr/plugins/imgproc/histbin.cpp

This reverts commit 7e1cff9ce5482b358bcfed89d02b6d011bd17f33.
This means Bin will remain as HistBin.
@sklum @JordanCheney

Revert "Rename histbin to bin"

---

openbr/core/core.cpp
openbr/openbr_plugin.h
openbr/plugins/core/loadstore.cpp

This commit is re: #344.
Consider a case where a partial model is trained, and serialized using load/store, then the complete algorithm is trained using that submodel, and saved as a complete algorithm (the output of -train):
br -algorithm "<Submodel>+OtherThings... " -train data finalModel
if the combined model is subsequently loaded, by specifying a relative or absolute path (i.e. not just loaded from the same directory), the submodel will not be found (since it is referred to in finalModel by its local name). i.e. 
br -algorithm /path/to/finalModel -enroll something
will not work.
This commit addresses that issue by also searching for sub-models in the paths were algorithms are successfully loaded from

Look for sub-models in directories algorithms were found in 

---

openbr/plugins/cmake/stasm4.cmake
share/openbr/cmake/FindStasm4.cmake

It ended up being way easier to fix some of the long standing problems related to `stasm`.  Thus, this branch:
* Simplifies how `stasm` is built into `openbr` by just including all the source.  To some extent this was happening before but it wasn't correctly done.
* Fixes the `Stasm_DIR` issue where cmake was finding an incorrect path.

Better stasm inclusion/compilation

---

openbr/plugins/metadata/grid.cpp

This branch adds the `border` property which allows a grid to be placed within a region of the entire src matrix as opposed to the whole matrix.  @jklontz any qualms?

Added border property

---

openbr/openbr_plugin.h

In the old version of ```Factory::parameters()``` passing a string with parameter arguments like ```Example(property1=value1)``` caused a segfault. This PR fixes this.

Changed the behavior of Factory::parameters() to avoid a segfault

---

openbr/plugins/distance/fuse.cpp
openbr/plugins/distance/neglogplusone.cpp
openbr/plugins/distance/pipe.cpp
openbr/plugins/distance/sum.cpp
openbr/plugins/openbr_internal.h

This branch adds some optimizations in `Distance`s with one or more child `Distance`s such that if none of the child distances are trainable, the distance returns `false` for its `trainable` method skipping the need to project enrollment during training.  There is also some related cleanup of `FuseDistance`.

Updates to trainable distances

---

openbr/core/eval.cpp
openbr/core/plot.cpp

This PR introduces the Identification Error Tradeoff (IET) curve as described in the [NIST FRVT 2013] (http://biometrics.nist.gov/cs_links/face/frvt/frvt2013/NIST_8009.pdf) report for evaluating the open-set identification problem.  
Additionally, FAR/FPIR values are now sampled in a range based on the order of magnitude of impostor comparisons/searches.  This was done in order to keep consistency of sampling points across testing splits, which are assumed to generally have the same order of magnitude of comparisons.

Add IET, changed ROC sampling

---

openbr/openbr_plugin.cpp

In an algorithm string along the lines of `Transform1+Transform2/Transform3+Transform4`, if either `Transform2` or `Transform3` sets the `fte` flag, it will not be present in the `Template`s passed to `Transform4` because of the logic in the various `Fork::project` calls.  This is because the `Template`s passed through a given child `Transform` of fork are merged with the original file and nothing handles the `fte` flag in these functions.  This branch changes that.

FTE in File::append

---

openbr/plugins/gallery/binary.cpp

@caotto @jklontz per our earlier convo.  My expectation is that the algorithm string should be able to handle removal of specific metadata in the case of successful enrollment.  This change constitutes a catch-all in the case of an `fte`.

Not storing cv::Mat metadata when fte

---

app/br/br.cpp
openbr/core/bee.cpp
openbr/core/core.cpp
openbr/openbr_plugin.cpp
openbr/openbr_plugin.h
openbr/plugins/core/crossvalidate.cpp
openbr/plugins/output/eval.cpp

This PR allows the user to specify a `bootStrap` seed to randomly split a dataset into training/testing sets based on a partition `inputVariable`.  
This could be used as a quick one-off with a seed of your choosing, or possibly over a set of numbers, say (1..10) within a script, for example:
```
for i in {1..10}
do
br -crossValidate 1 -algorithm "CrossValidate(description=$ALG,bootStrap=${i}):CrossValidate+Dist" -train target.xml query.xml model
br -crossValidate 1 -algorithm model -enroll target.xml target.gal
br -crossValidate 1 -algorithm model -enroll query.xml query.gal
br -crossValidate 1 -algorithm model -compare target.gal query.gal results%1.eval
mv results0.csv Algorithm_Split/results_${i}.csv
done
br -plot Algorithm_Split/* results.pdf[smooth=Split]
```
This is useful for …

Random test/train split in TemplateList::Partition

---

openbr/core/opencvutils.cpp
openbr/core/opencvutils.h

Allows the serialization of OpenCV objects that derive from the Algorithm object. Currently only the CvStatModel is supported.

Serialize algorithm

---

openbr/plugins/classification/caffe.cpp

@caotto. This has 2 parts, 1) Changes we talked about in the previous PR, namely change to MetaTransform and check if the first layer is a MemoryDataLayer. 2) A second caffe classifier transform. CaffeFV assumes output is a feature vector, CaffeClassifier assumes output is a score distribution for the input belonging to a range of classes. It finds the maximum score of the output nodes and stores the index as the label and the score as the confidence.

Caffe classifier

---

docs/docs/api_docs/c_api/functions.md

`br` instructs user to check API documentation for list of dependent packages.  One of the listed packages is `jpg` which doesn't exist in any R package repo.  Attempted to install `jpeg` package and plotting (i.e. `br -plot Eigenfaces.csv Eigenfaces.pdf`) works as expected.
Briefly looked through the rest of the API specs and it appears that these are all the references.

Fixed invalid R install packages in API docs

---

openbr/core/eval.cpp

Updates EvalDetection to ignore predicted bounding boxes associated with ground truth boxes that are beyond the specified thresholds.  @JordanCheney looks like the logic for this was already there but not being used.

EvalDetection change.

---

app/br/br.cpp
openbr/openbr.cpp
openbr/openbr.h
openbr/plugins/cmake/network.cmake

Per discussion in 
https://github.com/biometrics/openbr/commit/56b776899118a15aaaf85810d53f15c1a2de3fcc
multiprocess support was broken by the removal of br_slave_process, and there was no deep reason why this was necessary.
This branch re-introduces it, but only enables it when BR_WITH_QTNETWORK is on, so using qtnetwork can remain off by default. 
@jklontz, @sklum  care to review?

Fix multiprocess support

---

docs/docs/install.md

It takes a long time to build OpenCV with CUDA.
Maybe it's not necessary to use CUDA on OpenBR.

(Document) Windows Install:  Build OpenCV without CUDA

---

openbr/core/core.cpp

per discussion in #488, adjust behavior of "append" flat during enrollment to exclude files at the beginning rather than end of processing
@sklum care to review? This appears to work for me based on some brief testing on MEDS data, but you should check for your usecase.

Adjust enroll append behavior

---

openbr/openbr_plugin.cpp

Possible fix for runtime crash when using qt 5.7.  Without this fix -- crash happens because QObject::setProperty(qPrintable(name), value) returns false within Object::setProperty

Possible fix for run-time crash when using qt 5.7

---

openbr/core/opencvutils.cpp

This was causing issues on Android where a temp file couldn't be created. Solution seems to work great so I'm going to go ahead an merge it. @sklum FYI.

load a stat model from memory without creating a temporary file

---

app/br/br.cpp
openbr/core/eval.cpp
openbr/core/eval.h
openbr/core/plot.cpp
openbr/core/plot.h
openbr/openbr.cpp
openbr/openbr.h

This PR makes 2 changes to evalEER and adds a new, corresponding, plotEER method. The C API and command line tool are updated to support the new function.
Changes are:
1. Change how operating points are computed to mirror eval (i.e. operating points are added only if both the true positive AND false positive count changes). This fixes a bug where successive operating points could have the same FAR, which caused nan results in the output.
2. Change the optional pdf argument to a CSV argument (again mirroring eval) so that results are written as CSVs and can be combined to show multiple results on the same plot

Changes to evalEER

---

openbr/core/eval.cpp
openbr/core/evalutils.cpp
openbr/core/evalutils.h

Update sorted detections to take the overlap threshold into account when sorting. Previously, only overlap was used to sort SortedDetections and subsequent assignment of ResolvedDetections was dependent on the overlap ordering. This allowed very low confidence predictions with higher overlap to be assigned to ground truth detections instead of higher confidence predictions with slightly worse overlap. The new methodology is to sort by overlap up to the overlap threshold, but then switch to sorting by confidence.

Overlap Change

---

CMakeLists.txt

To support vcpkg, the hard coded path was no longer valid. Also manages opencv thirdparty libraries.

Update opencv linking for iOS

---

CMakeLists.txt

Avoids warning on macOS/Apple clang

Move `-Wno-terminate` compiler flag to GCC only

---

openbr/core/boost.cpp
openbr/openbr_plugin.h
openbr/plugins/metadata/stopwatch.cpp

QTime `elapsed()` is deprecated, updating to QElapsedTimer is recommended.  `QElapsedTimer` was added in Qt v4.7.

update QTime to QElapsedTimer
